# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customFlowRateUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustDlg(object):
    def setupUi(self, CustDlg):
        CustDlg.setObjectName("CustDlg")
        CustDlg.resize(200, 80)
        self.custFlowDsb = QtWidgets.QDoubleSpinBox(CustDlg)
        self.custFlowDsb.setGeometry(QtCore.QRect(10, 40, 110, 25))
        self.custFlowDsb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.custFlowDsb.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.custFlowDsb.setMaximum(999999.0)
        self.custFlowDsb.setSingleStep(50.0)
        self.custFlowDsb.setProperty("value", 0.0)
        self.custFlowDsb.setObjectName("custFlowDsb")
        self.custCkb = QtWidgets.QCheckBox(CustDlg)
        self.custCkb.setGeometry(QtCore.QRect(10, 10, 150, 20))
        self.custCkb.setObjectName("custCkb")
        self.confirmPb = QtWidgets.QPushButton(CustDlg)
        self.confirmPb.setGeometry(QtCore.QRect(130, 40, 60, 25))
        self.confirmPb.setObjectName("confirmPb")

        self.retranslateUi(CustDlg)
        QtCore.QMetaObject.connectSlotsByName(CustDlg)
        CustDlg.setTabOrder(self.custFlowDsb, self.confirmPb)
        CustDlg.setTabOrder(self.confirmPb, self.custCkb)

    def retranslateUi(self, CustDlg):
        _translate = QtCore.QCoreApplication.translate
        CustDlg.setWindowTitle(_translate("CustDlg", "Fondo Scala"))
        self.custFlowDsb.setSuffix(_translate("CustDlg", " NmL/min"))
        self.custCkb.setText(_translate("CustDlg", "Fondo Scala personalizzato"))
        self.confirmPb.setText(_translate("CustDlg", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustDlg = QtWidgets.QDialog()
    ui = Ui_CustDlg()
    ui.setupUi(CustDlg)
    CustDlg.show()
    sys.exit(app.exec_())
