# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(369, 518)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.regTW = QtWidgets.QTableWidget(self.centralwidget)
        self.regTW.setGeometry(QtCore.QRect(20, 10, 321, 311))
        self.regTW.setObjectName("regTW")
        self.regTW.setColumnCount(3)
        self.regTW.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.regTW.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.regTW.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.regTW.setHorizontalHeaderItem(2, item)
        self.refreshPb = QtWidgets.QPushButton(self.centralwidget)
        self.refreshPb.setGeometry(QtCore.QRect(260, 330, 75, 23))
        self.refreshPb.setObjectName("refreshPb")
        self.flowSetDsb = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.flowSetDsb.setGeometry(QtCore.QRect(90, 360, 140, 25))
        self.flowSetDsb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.flowSetDsb.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.flowSetDsb.setMaximum(9999.99)
        self.flowSetDsb.setSingleStep(50.0)
        self.flowSetDsb.setProperty("value", 9999.99)
        self.flowSetDsb.setObjectName("flowSetDsb")
        self.flowSetLbl = QtWidgets.QLabel(self.centralwidget)
        self.flowSetLbl.setGeometry(QtCore.QRect(20, 360, 70, 25))
        self.flowSetLbl.setObjectName("flowSetLbl")
        self.sendPb = QtWidgets.QPushButton(self.centralwidget)
        self.sendPb.setGeometry(QtCore.QRect(260, 360, 75, 23))
        self.sendPb.setObjectName("sendPb")
        self.flowReadDsb = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.flowReadDsb.setGeometry(QtCore.QRect(90, 330, 140, 25))
        self.flowReadDsb.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.flowReadDsb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.flowReadDsb.setReadOnly(True)
        self.flowReadDsb.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.flowReadDsb.setMaximum(9999.99)
        self.flowReadDsb.setSingleStep(50.0)
        self.flowReadDsb.setProperty("value", 9999.99)
        self.flowReadDsb.setObjectName("flowReadDsb")
        self.flowReadLbl = QtWidgets.QLabel(self.centralwidget)
        self.flowReadLbl.setGeometry(QtCore.QRect(20, 330, 70, 25))
        self.flowReadLbl.setObjectName("flowReadLbl")
        self.flowRateDsb = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.flowRateDsb.setGeometry(QtCore.QRect(90, 390, 140, 25))
        self.flowRateDsb.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.flowRateDsb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.flowRateDsb.setReadOnly(True)
        self.flowRateDsb.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.flowRateDsb.setMaximum(9999.99)
        self.flowRateDsb.setSingleStep(50.0)
        self.flowRateDsb.setProperty("value", 9999.99)
        self.flowRateDsb.setObjectName("flowRateDsb")
        self.flowRateLbl = QtWidgets.QLabel(self.centralwidget)
        self.flowRateLbl.setGeometry(QtCore.QRect(20, 390, 70, 25))
        self.flowRateLbl.setObjectName("flowRateLbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 369, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.regTW.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.regTW.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Registro"))
        item = self.regTW.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Valore"))
        self.refreshPb.setText(_translate("MainWindow", "Refresh"))
        self.flowSetDsb.setSuffix(_translate("MainWindow", " NmL/min"))
        self.flowSetLbl.setText(_translate("MainWindow", "Set"))
        self.sendPb.setText(_translate("MainWindow", "Send"))
        self.flowReadDsb.setSuffix(_translate("MainWindow", " NmL/min"))
        self.flowReadLbl.setText(_translate("MainWindow", "Read"))
        self.flowRateDsb.setSuffix(_translate("MainWindow", " NmL/min"))
        self.flowRateLbl.setText(_translate("MainWindow", "Flow Rate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
