# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_comDlg(object):
    def setupUi(self, comDlg):
        comDlg.setObjectName("comDlg")
        comDlg.resize(171, 296)
        self.label_9 = QtWidgets.QLabel(comDlg)
        self.label_9.setGeometry(QtCore.QRect(120, 130, 41, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(comDlg)
        self.label_11.setGeometry(QtCore.QRect(120, 150, 41, 16))
        self.label_11.setObjectName("label_11")
        self.label_5 = QtWidgets.QLabel(comDlg)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 100, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.comCb = QtWidgets.QComboBox(comDlg)
        self.comCb.setGeometry(QtCore.QRect(20, 30, 131, 22))
        self.comCb.setObjectName("comCb")
        self.label_8 = QtWidgets.QLabel(comDlg)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 100, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(comDlg)
        self.label_6.setGeometry(QtCore.QRect(120, 90, 41, 16))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(comDlg)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 100, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.testPb = QtWidgets.QPushButton(comDlg)
        self.testPb.setGeometry(QtCore.QRect(10, 260, 75, 23))
        self.testPb.setObjectName("testPb")
        self.label_7 = QtWidgets.QLabel(comDlg)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 100, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.confirmPb = QtWidgets.QPushButton(comDlg)
        self.confirmPb.setGeometry(QtCore.QRect(90, 260, 75, 23))
        self.confirmPb.setObjectName("confirmPb")
        self.label_4 = QtWidgets.QLabel(comDlg)
        self.label_4.setGeometry(QtCore.QRect(120, 70, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(comDlg)
        self.label_10.setGeometry(QtCore.QRect(120, 110, 41, 16))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(comDlg)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 100, 16))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label = QtWidgets.QLabel(comDlg)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(comDlg)
        self.line.setGeometry(QtCore.QRect(10, 180, 150, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_13 = QtWidgets.QLabel(comDlg)
        self.label_13.setGeometry(QtCore.QRect(0, 190, 100, 25))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.slaveSb = QtWidgets.QSpinBox(comDlg)
        self.slaveSb.setGeometry(QtCore.QRect(110, 190, 30, 25))
        self.slaveSb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slaveSb.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.slaveSb.setMinimum(1)
        self.slaveSb.setProperty("value", 1)
        self.slaveSb.setObjectName("slaveSb")
        self.logLe = QtWidgets.QLineEdit(comDlg)
        self.logLe.setGeometry(QtCore.QRect(10, 230, 151, 20))
        self.logLe.setObjectName("logLe")

        self.retranslateUi(comDlg)
        QtCore.QMetaObject.connectSlotsByName(comDlg)

    def retranslateUi(self, comDlg):
        _translate = QtCore.QCoreApplication.translate
        comDlg.setWindowTitle(_translate("comDlg", "Dialog"))
        self.label_9.setText(_translate("comDlg", "1"))
        self.label_11.setText(_translate("comDlg", "Nessuno"))
        self.label_5.setText(_translate("comDlg", "Bit di dati:"))
        self.label_8.setText(_translate("comDlg", "Bit di stop:"))
        self.label_6.setText(_translate("comDlg", "8"))
        self.label_3.setText(_translate("comDlg", "Baud Rate:"))
        self.testPb.setText(_translate("comDlg", "Test"))
        self.label_7.setText(_translate("comDlg", "Parità:"))
        self.confirmPb.setText(_translate("comDlg", "OK"))
        self.label_4.setText(_translate("comDlg", "38400"))
        self.label_10.setText(_translate("comDlg", "Nessuna"))
        self.label_12.setText(_translate("comDlg", "Controllo di flusso:"))
        self.label.setText(_translate("comDlg", "Seleziona la porta COM"))
        self.label_13.setText(_translate("comDlg", "Slave:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    comDlg = QtWidgets.QDialog()
    ui = Ui_comDlg()
    ui.setupUi(comDlg)
    comDlg.show()
    sys.exit(app.exec_())
